#!/bin/sh
export PATH=/bin

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
[ -d /run ] || mkdir /run
[ -d /root ] || mkdir /root
[ -d /etc ] || mkdir /etc
[ -d /home ] || mkdir /home

echo 'root:x:0:0:root:/root:/bin/sh' > /etc/passwd
echo 'root:x:0:' > /etc/group
chmod 644 /etc/passwd
chmod 644 /etc/group

adduser user --disabled-password

chown -R root:root /
chmod 700 /flag
chmod u+s /bin/busybox 

chmod 700 -R /root
chown user:user -R /home/user
chmod 777 /home/user
chmod 755 /dev

mkdir -p /var/lock
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t proc -o nodev,noexec,nosuid proc /proc
ln -sf /proc/mounts /etc/mtab
mount -t devtmpfs -o nosuid,mode=0755 udev /dev
mkdir -p /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true
mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run

insmod /mod.ko
mknod /dev/mod c 100 0
chmod o+rw /dev/mod

echo 1 > /proc/sys/kernel/kptr_restrict
echo 1 > /proc/sys/kernel/perf_event_paranoid
#echo 0 > /proc/sys/kernel/kptr_restrict
#echo 0 > /proc/sys/kernel/perf_event_paranoid

cat <<EOF
Boot took $(cut -d' ' -f1 /proc/uptime) seconds

           _  
 |  _. |_ (_| 
 | (_| |_)  | 
              

EOF

#setsid cttyhack setuidgid 0 sh
setsid cttyhack setuidgid 1000 sh

umount /proc
umount /sys

halt -d 1 -n -f
